CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(30) UNIQUE NOT NULL,
    nombres TEXT NOT NULL,
    apellidos TEXT NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    nombre_completo TEXT GENERATED ALWAYS AS (
        nombres || ' ' || apellidos
    ) STORED,
    grupos TEXT[] NOT NULL DEFAULT ARRAY['user']::TEXT[] CHECK (
        grupos <@ ARRAY['user', 'admin','superadmin']::TEXT[] 
        AND cardinality(grupos) > 0
    ),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS credenciales (
    id_usuario INTEGER PRIMARY KEY REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    password_hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tareas (
    id_tarea INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_creador INTEGER NOT NULL REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    grupo TEXT NOT NULL CHECK (grupo IN ('user', 'admin', 'superadmin')),
    titulo VARCHAR(100) NOT NULL,
    descripcion TEXT,
    prioridad VARCHAR(10) NOT NULL DEFAULT '1:media' CHECK (prioridad IN ('0:baja', '1:media', '2:alta')),
    creada TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    terminada TIMESTAMPTZ,
    estado TEXT GENERATED ALWAYS AS (
        CASE 
            WHEN terminada IS NOT NULL THEN 'Cerrada' 
            ELSE 'Abierta' 
        END
    ) STORED
);

WITH nuevos_usuarios AS (
    INSERT INTO usuarios (username, nombres, apellidos, fecha_nacimiento, grupos) 
    VALUES
        ('superadmin', 'EL', 'SUPERADMIN', '1995-12-08', ARRAY['superadmin']),
        ('admin', 'Administrador', 'Sistema', '1985-03-15', ARRAY['admin', 'user']),
        ('user', 'Un', 'User', '1993-07-22', ARRAY['user']),
        ('mgonzalez', 'Martín', 'González', '1992-07-22', ARRAY['user']),
        ('srodriguez', 'Sofía', 'Rodríguez', '1995-11-08', ARRAY['user']),
        ('lfernandez', 'Lucas', 'Fernández', '2010-01-30', ARRAY['user'])
    RETURNING id_usuario
)
INSERT INTO credenciales (id_usuario, password_hash)
SELECT id_usuario, crypt('Contraseña1', gen_salt('bf'))
FROM nuevos_usuarios;

INSERT INTO tareas (id_creador, grupo, titulo, descripcion, prioridad, creada, terminada) 
VALUES
    -- Tareas para el grupo 'superadmin'
    (1, 'superadmin', 'Promover a usuario jperez a rol admin', 'Aprobar la solicitud de permisos elevados tras auditoría de seguridad.', '2:alta', CURRENT_TIMESTAMP - INTERVAL '2 days', NULL),
    (1, 'superadmin', 'Depurar logs de auditoría del sistema', 'Realizar purga de registros antiguos mayores a 90 días en la base de datos.', '1:media', CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP - INTERVAL '1 day'),
    (1, 'superadmin', 'Renovar llaves maestras de cifrado JWT', 'Rotación anual de secretos para tokens de autenticación.', '2:alta', CURRENT_TIMESTAMP - INTERVAL '1 day', NULL),
    (1, 'superadmin', 'Crear cuenta de administrador para auditoría externa', 'Dar de alta al usuario temporal audit_ext con rol admin.', '0:baja', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP - INTERVAL '2 days'),

    -- Tareas para el grupo 'admin'
    (1, 'admin', 'Revisar reportes de usuarios bloqueados', 'Verificar intentos fallidos de inicio de sesión de la última semana.', '1:media', CURRENT_TIMESTAMP - INTERVAL '12 hours', NULL),
    (1, 'admin', 'Actualizar documentación de la API', 'Sincronizar la especificación Swagger con las rutas de Fastify recientemente agregadas.', '0:baja', CURRENT_TIMESTAMP - INTERVAL '3 days', NULL),
    (1, 'admin', 'Monitorear uso de recursos del servidor', 'Evaluar consumo de CPU y memoria tras el último despliegue.', '2:alta', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 hours'),
    (1, 'admin', 'Mantenimiento programado de base de datos', 'Ejecutar VACUUM ANALYZE durante la ventana de bajo tráfico.', '1:media', CURRENT_TIMESTAMP - INTERVAL '4 days', NULL),

    -- Tareas para el grupo 'user'
    (1, 'user', 'Verificar configuración del repositorio', 'Verificar Verificar que el proyecto levanta y funciona sin problemas de configuraciòn.', '0:baja', CURRENT_TIMESTAMP - INTERVAL '10 days', CURRENT_TIMESTAMP - INTERVAL '9 days'),
    (1, 'user', 'Seleccionar método de pago', 'Seleccionar y fundamente el método de pago a usar en el proyecto.', '2:alta', CURRENT_TIMESTAMP - INTERVAL '6 hours', NULL),
    (1, 'user', 'Tests', 'Revisar que están funcionando los tests unitarios.', '1:media', CURRENT_TIMESTAMP - INTERVAL '2 days', NULL),
    (1, 'user', 'Tests', 'Revisar los tests de integración.', '0:baja', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '4 hours');
